/**
 * run-export-packaging.ts — Compress assets and generate tool-specific export packages.
 * Creates .zip archives with README, quality reports, style specs, prompts, assets, configs, and guides.
 *
 * Run: bun run scripts/run-export-packaging.ts --tool "figma" --assets-dir "..." --output "export.zip"
 */

import { createWriteStream } from "node:fs";
import { mkdir, readdir, stat } from "node:fs/promises";
import { extname, join } from "node:path";
import archiver from "archiver";
import { Console, Effect, pipe } from "effect";

// --- Types ---

type ExportTool =
  | "figma"
  | "framer"
  | "webflow"
  | "wordpress"
  | "shopify"
  | "squarespace"
  | "notion"
  | "canva"
  | "generic";

interface ExportInput {
  readonly tool: ExportTool;
  readonly assetsDir: string;
  readonly output: string;
}

interface ExportResult {
  readonly zip_path: string;
  readonly file_count: number;
  readonly total_size: number;
}

// --- Tool-Specific Config Templates ---

const TOOL_CONFIGS: Record<
  ExportTool,
  { readme_header: string; config_format: string; accepts: string[] }
> = {
  figma: {
    readme_header: "Figma Import Guide",
    config_format: "json",
    accepts: ["png", "jpg", "svg", "webp"],
  },
  framer: {
    readme_header: "Framer Import Guide",
    config_format: "json",
    accepts: ["png", "jpg", "svg", "webp", "mp4", "gif"],
  },
  webflow: {
    readme_header: "Webflow Import Guide",
    config_format: "json",
    accepts: ["png", "jpg", "svg", "webp", "mp4", "gif", "css"],
  },
  wordpress: {
    readme_header: "WordPress Import Guide",
    config_format: "php",
    accepts: ["png", "jpg", "svg", "webp", "mp4", "css", "js"],
  },
  shopify: {
    readme_header: "Shopify Theme Import Guide",
    config_format: "json",
    accepts: ["png", "jpg", "svg", "webp", "css", "liquid"],
  },
  squarespace: {
    readme_header: "Squarespace Import Guide",
    config_format: "json",
    accepts: ["png", "jpg", "svg", "webp", "css"],
  },
  notion: {
    readme_header: "Notion Import Guide",
    config_format: "md",
    accepts: ["png", "jpg", "svg", "webp"],
  },
  canva: {
    readme_header: "Canva Import Guide",
    config_format: "json",
    accepts: ["png", "jpg", "svg"],
  },
  generic: {
    readme_header: "Design Asset Export",
    config_format: "json",
    accepts: ["png", "jpg", "svg", "webp", "mp4", "gif", "glb", "css", "js"],
  },
};

// --- Document Generators ---

export function generateReadme(tool: ExportTool, fileCount: number, totalSize: number): string {
  const config = TOOL_CONFIGS[tool];
  return [
    `# ${config.readme_header}`,
    ``,
    `Generated by One-of-a-Kind Design on ${new Date().toISOString().split("T")[0]}`,
    ``,
    `## Contents`,
    ``,
    `- **assets/**: ${fileCount} design assets (${formatBytes(totalSize)})`,
    `- **config/**: Tool-specific configuration files`,
    `- **prompts/**: Generation prompts used for each asset`,
    `- **guides/**: Implementation guides and best practices`,
    `- **QUALITY-REPORT.md**: Automated quality scores`,
    `- **STYLE-SPEC.md**: Design system specification`,
    ``,
    `## Import Instructions`,
    ``,
    ...getImportInstructions(tool),
    ``,
    `## Accepted Formats`,
    ``,
    config.accepts.map((fmt) => `- .${fmt}`).join("\n"),
    ``,
    `## Quality Guarantee`,
    ``,
    `All assets passed the One-of-a-Kind quality gate (minimum 7.0/10 composite score).`,
    `See QUALITY-REPORT.md for detailed per-asset scoring.`,
  ].join("\n");
}

function getImportInstructions(tool: ExportTool): string[] {
  const instructions: Record<ExportTool, string[]> = {
    figma: [
      "1. Open your Figma project",
      "2. Drag and drop assets from the `assets/` folder",
      "3. Apply styles from `config/figma-tokens.json` using Tokens Studio plugin",
      "4. Reference `guides/figma-component-guide.md` for component structure",
    ],
    framer: [
      "1. Open your Framer project",
      "2. Upload assets via the Assets panel",
      "3. Import motion presets from `config/framer-motion.json`",
      "4. Reference `guides/framer-setup-guide.md` for layout",
    ],
    webflow: [
      "1. Open your Webflow project",
      "2. Upload assets via the Asset Manager",
      "3. Import classes from `config/webflow-classes.json`",
      "4. Paste custom CSS from `config/custom.css` into Project Settings",
    ],
    wordpress: [
      "1. Upload the theme zip via Appearance > Themes > Add New",
      "2. Activate the theme",
      "3. Import assets via Media Library",
      "4. Configure using `config/theme-options.php`",
    ],
    shopify: [
      "1. Go to Online Store > Themes > Add theme",
      "2. Upload assets to theme assets",
      "3. Apply settings from `config/settings_data.json`",
      "4. Reference `guides/shopify-theme-guide.md`",
    ],
    squarespace: [
      "1. Go to Design > Custom CSS",
      "2. Paste contents of `config/custom.css`",
      "3. Upload images via the Asset Library",
      "4. Reference `guides/squarespace-guide.md`",
    ],
    notion: [
      "1. Create a new Notion page or database",
      "2. Upload images from `assets/` directly to blocks",
      "3. Reference `guides/notion-layout-guide.md` for structure",
    ],
    canva: [
      "1. Open Canva and create a new design",
      "2. Upload assets via Uploads panel",
      "3. Apply brand colors from `config/brand-palette.json`",
    ],
    generic: [
      "1. Review the `assets/` directory for all generated files",
      "2. Consult `config/` for implementation details",
      "3. Follow `guides/` for integration best practices",
    ],
  };
  return instructions[tool];
}

function generateQualityReport(): string {
  return [
    "# Quality Report",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    "## Scoring Summary",
    "",
    "| Metric | Score | Status |",
    "|--------|-------|--------|",
    "| Anti-Slop Gate | -- | Pending |",
    "| Code Standards | -- | Pending |",
    "| Asset Quality | -- | Pending |",
    "| Prompt Alignment | -- | Pending |",
    "| Aesthetic | -- | Pending |",
    "| Style Fidelity | -- | Pending |",
    "| Distinctiveness | -- | Pending |",
    "",
    "Scores are populated during the quality validation pipeline.",
    "See `score-output-quality.ts` for composite scoring.",
  ].join("\n");
}

function generateStyleSpec(): string {
  return [
    "# Style Specification",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    "## Design Tokens",
    "",
    "Design tokens and style parameters for this export are defined",
    "in the `config/` directory in the tool-appropriate format.",
    "",
    "## Typography",
    "",
    "Font selections, scale, and hierarchy rules are specified in the style config.",
    "",
    "## Color System",
    "",
    "Primary, secondary, and accent colors with their semantic roles",
    "are included in the configuration files.",
    "",
    "## Motion",
    "",
    "Animation parameters, easing curves, and transition specifications",
    "are defined in the motion config where applicable.",
  ].join("\n");
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// --- Archive Creation ---

export function createZipArchive(
  input: ExportInput,
  files: Array<{ path: string; relativePath: string; size: number }>,
): Effect.Effect<ExportResult, Error> {
  const toolConfig = TOOL_CONFIGS[input.tool];
  const totalSize = files.reduce((sum, f) => sum + f.size, 0);

  return Effect.tryPromise({
    try: async () => {
      // Ensure output directory exists
      const outputDir = input.output.substring(0, input.output.lastIndexOf("/"));
      if (outputDir) {
        try {
          await mkdir(outputDir, { recursive: true });
        } catch {
          /* directory may exist */
        }
      }

      const output = createWriteStream(input.output);
      const archive = archiver("zip", { zlib: { level: 9 } });

      const done = new Promise<void>((resolve, reject) => {
        output.addListener("close", resolve);
        archive.addListener("error", reject);
      });

      archive.pipe(output);

      // Add asset files
      const acceptedExts = new Set(toolConfig.accepts.map((a) => `.${a}`));
      let fileCount = 0;

      for (const file of files) {
        const ext = extname(file.relativePath).toLowerCase();
        if (acceptedExts.has(ext) || acceptedExts.has("*")) {
          archive.file(file.path, { name: `assets/${file.relativePath}` });
          fileCount++;
        }
      }

      // Add generated documents
      const readme = generateReadme(input.tool, fileCount, totalSize);
      archive.append(readme, { name: "README.md" });
      fileCount++;

      const qualityReport = generateQualityReport();
      archive.append(qualityReport, { name: "QUALITY-REPORT.md" });
      fileCount++;

      const styleSpec = generateStyleSpec();
      archive.append(styleSpec, { name: "STYLE-SPEC.md" });
      fileCount++;

      // Add empty directories for structure
      archive.append("", { name: "prompts/.gitkeep" });
      archive.append("", { name: "config/.gitkeep" });
      archive.append("", { name: "guides/.gitkeep" });
      fileCount += 3;

      await archive.finalize();
      await done;

      const zipStat = await stat(input.output);
      return {
        zip_path: input.output,
        file_count: fileCount,
        total_size: zipStat.size,
      } satisfies ExportResult;
    },
    catch: (e) => new Error(`Export packaging failed: ${e}`),
  });
}

// --- CLI Entry ---

const program = Effect.gen(function* () {
  const args = process.argv.slice(2);
  const getArg = (flag: string): string | undefined => {
    const idx = args.indexOf(flag);
    return idx >= 0 ? args[idx + 1] : undefined;
  };

  const tool = (getArg("--tool") ?? "generic") as ExportTool;
  const assetsDir = getArg("--assets-dir");
  const output = getArg("--output") ?? `export-${tool}-${Date.now()}.zip`;

  if (!assetsDir) return yield* Effect.fail(new Error("--assets-dir is required"));

  const validTools = Object.keys(TOOL_CONFIGS) as ExportTool[];
  if (!validTools.includes(tool)) {
    return yield* Effect.fail(new Error(`Invalid tool: ${tool}. Valid: ${validTools.join(", ")}`));
  }

  const noEntries = (): never[] => [];
  const noStat = (): null => null;
  const files = yield* Effect.tryPromise({
    try: async () => {
      const collected: Array<{ path: string; relativePath: string; size: number }> = [];
      const walkDir = async (currentDir: string, prefix: string): Promise<void> => {
        const entries = await readdir(currentDir, { withFileTypes: true }).catch(noEntries);
        for (const entry of entries) {
          const fullPath = join(currentDir, entry.name);
          if (entry.isDirectory()) {
            await walkDir(fullPath, join(prefix, entry.name));
          } else {
            const fileStat = await stat(fullPath).catch(noStat);
            if (fileStat) {
              collected.push({
                path: fullPath,
                relativePath: join(prefix, entry.name),
                size: fileStat.size,
              });
            }
          }
        }
      };
      await walkDir(assetsDir, "");
      return collected;
    },
    catch: (e) => new Error(`Failed to scan assets directory: ${e}`),
  });

  if (files.length === 0) {
    return yield* Effect.fail(new Error(`No files found in assets directory: ${assetsDir}`));
  }

  const result = yield* createZipArchive({ tool, assetsDir, output }, files);

  yield* Console.log(JSON.stringify(result, null, 2));
});

if (import.meta.main) {
  pipe(
    program,
    Effect.catchAll((error) =>
      Effect.sync(() => {
        console.error(`Export packaging failed: ${error}`);
        process.exit(1);
      }),
    ),
    Effect.runPromise,
  );
}
